### ISSUE TITLE
Re-rendering with new data doesn't work

### ISSUE THREAD

**Issue by robtweed** [rodrigowirth/react-flot#6] opened 2017-09-12 16:37 UTC
If I add a new data point to the data object and change state to re-render, the graph isn't updated.  The reason is this code in ReactFlot.js

`        key: 'componentWillReceiveProps',
        value: function componentWillReceiveProps(nextProps) {
            if (!(0, _deepEqual2.default)(nextProps.data, this.props.data)) {
                this.draw(null, nextProps.data);
            }
        }
`

nextProps.data and this.props.data are always identical.  I fixed this by removing the condition and always drawing:

`        key: 'componentWillReceiveProps',
        value: function componentWillReceiveProps(nextProps) {
              this.draw(null, nextProps.data);
        }
`

**Comment by rodrigowirth** [comment] 2017-10-03 19:54
Hi @robtweed,

Do you have an example? I am trying to reproduce this issue.

**Comment by rodrigowirth** [comment] 2017-10-05 16:21
Hi @robtweed,

I could not reproduce this issue. In this commit, I added an example using the state.
https://github.com/rodrigowirth/react-flot/commit/70bf69b55296587c7414545acf65e92b01550748

I am going to close the issue. If you need any help, please let me know.

**Closed as completed by rodrigowirth** 2017-10-05 16:21 UTC
